import {
  admin,
  anonimo,
  cadastrador,
  gestorEscolar,
  gestorEstratLocal,
  gestorEstratNacional,
  gestorEstratRegional,
  gestorOpLocal,
  gestorOpNacional,
  gestorOpRegional,
  gestorTatLocal,
  gestorTatNacional,
  gestorTatRegional,
  professor,
  publicador,
  suportePedagogico,
  suporteTecnico,
  visitante,
} from './Role';

export default [
  admin,
  anonimo,
  cadastrador,
  gestorEscolar,
  gestorEstratLocal,
  gestorEstratNacional,
  gestorEstratRegional,
  gestorOpLocal,
  gestorOpNacional,
  gestorOpRegional,
  gestorTatLocal,
  gestorTatNacional,
  gestorTatRegional,
  professor,
  publicador,
  suportePedagogico,
  suporteTecnico,
  visitante,
];
