import defaultReportPermissions from '../../constants/defaultReportPermissions';

export default [
  {
    action: 'getProjectsReport',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/projects',
    roles: defaultReportPermissions,
  },
  {
    action: 'downloadProjectsCSV',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/projects/download',
    roles: defaultReportPermissions,
  },
  {
    action: 'downloadMessagesCSV',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/messages/download',
    roles: defaultReportPermissions,
  },
  {
    action: 'getMessagesReport',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/messages',
    roles: defaultReportPermissions,
  },
  {
    action: 'getInitiativesReport',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/initiatives',
    roles: defaultReportPermissions,
  },
  {
    action: 'downloadInitiativesCSV',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/initiatives/download',
    roles: defaultReportPermissions,
  },
  {
    action: 'getActivityDownloadsReport',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/downloads',
    roles: defaultReportPermissions,
  },
  {
    action: 'downloadActivityDownloadCSV',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/downloads/download',
    roles: defaultReportPermissions,
  },
  {
    action: 'getInteractivityReport',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/initiatives',
    roles: defaultReportPermissions,
  },
  {
    action: 'getInteractivityReport',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/interactivity',
    roles: defaultReportPermissions,
  },
  {
    action: 'downloadInteractivityCSV',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/interactivity/download',
    roles: defaultReportPermissions,
  },
  {
    action: 'getSurveyReport',
    controller: 'reports',
    isPrivate: true,
    method: 'post',
    path: '/survey',
    roles: defaultReportPermissions,
  },
  {
    action: 'downloadSurveyReport',
    controller: 'reports',
    isPrivate: true,
    method: 'post',
    path: '/survey/download',
    roles: defaultReportPermissions,
  },
  {
    action: 'getParticipantsReport',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/participants',
    roles: defaultReportPermissions,
  },
  {
    action: 'downloadParticipantsCSV',
    controller: 'reports',
    isPrivate: true,
    method: 'get',
    path: '/participants/download',
    roles: defaultReportPermissions,
  },
];
