import {
  admin,
  anonimo,
  infantil,
  cadastrador,
  gestorEscolar,
  gestorEstratLocal,
  gestorEstratNacional,
  gestorEstratRegional,
  gestorOpLocal,
  gestorOpNacional,
  gestorOpRegional,
  gestorTatLocal,
  gestorTatNacional,
  gestorTatRegional,
  professor,
  publicador,
  suportePedagogico,
  suporteTecnico,
  visitante,
  naoConfirmado
} from '@/infra/constants/profileRoles';

const parserRouter = (t: any) => [
  {
    label: t('components:Menu.pages.courses'),
    path: '/cursos',
    private: false,
    roles: [
      admin,
      anonimo,
      infantil,
      visitante,
      professor,
      gestorEscolar,
      gestorOpLocal,
      gestorOpRegional,
      gestorOpNacional,
      gestorTatLocal,
      gestorTatNacional,
      gestorTatRegional,
      gestorEstratLocal,
      gestorEstratNacional,
      gestorEstratRegional,
      cadastrador,
      publicador,
      suportePedagogico,
      suporteTecnico,
      naoConfirmado
    ],
  },
  {
    label: t('components:Menu.pages.projects'),
    path: '/projetos',
    private: false,
    roles: [
      admin,
      anonimo,
      infantil,
      cadastrador,
      gestorEscolar,
      gestorEstratLocal,
      gestorEstratNacional,
      gestorEstratRegional,
      gestorOpLocal,
      gestorOpNacional,
      gestorOpRegional,
      gestorTatLocal,
      gestorTatNacional,
      gestorTatRegional,
      professor,
      publicador,
      suportePedagogico,
      suporteTecnico,
      visitante,
      naoConfirmado
    ],
  },
  {
    label: t('components:Menu.pages.actions'),
    path: '/acoes',
    private: true,
    roles: [
      admin,
      gestorOpLocal,
      gestorOpNacional,
      gestorOpRegional,
      gestorEstratLocal,
      gestorEstratNacional,
      gestorEstratRegional,
      gestorTatLocal,
      gestorTatNacional,
      gestorTatRegional,
      publicador,
      cadastrador,
    ],
  },
  {
    label: t('components:Menu.pages.activities'),
    path: '/atividades',
    private: false,
    roles: [
      admin,
      anonimo,
      infantil,
      visitante,
      professor,
      gestorEscolar,
      gestorOpLocal,
      gestorOpRegional,
      gestorOpNacional,
      gestorTatLocal,
      gestorTatNacional,
      gestorTatRegional,
      gestorEstratLocal,
      gestorEstratNacional,
      gestorEstratRegional,
      cadastrador,
      publicador,
      suportePedagogico,
      suporteTecnico,
      naoConfirmado
    ],
  },
];

export default parserRouter;
