import allRolesPermission from '../../constants/allRolesPermission';
import { admin } from '../../constants/Role';

export default [
  {
    action: 'create',
    controller: 'courses',
    isPrivate: true,
    method: 'post',
    path: '/courses',
    roles: allRolesPermission,
  },
  {
    action: 'deleteCourse',
    controller: 'courses',
    isPrivate: true,
    method: 'delete',
    path: '/courses/:id',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'courses',
    isPrivate: true,
    method: 'put',
    path: '/courses',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSV',
    controller: 'courses',
    isPrivate: true,
    method: 'get',
    path: '/courses/download',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'courseImagesCarousel',
    isPrivate: true,
    method: 'post',
    path: '/courses/images',
    roles: allRolesPermission,
  },
  {
    action: 'setDefault',
    controller: 'courseImagesCarousel',
    isPrivate: true,
    method: 'post',
    path: '/courses/images/default',
    roles: allRolesPermission,
  },
  {
    action: 'deleteImage',
    controller: 'courseImagesCarousel',
    isPrivate: true,
    method: 'delete',
    path: '/courses/images/:id',
    roles: allRolesPermission,
  },
  {
    action: 'search',
    controller: 'courses',
    isPrivate: true,
    method: 'get',
    path: '/courses',
    roles: allRolesPermission,
  },
  {
    action: 'publish',
    controller: 'courses',
    isPrivate: true,
    method: 'post',
    path: '/courses/publish',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'courseAttachments',
    isPrivate: true,
    method: 'post',
    path: '/courses/attachments',
    roles: allRolesPermission,
  },
  {
    action: 'deleteAttachment',
    controller: 'courseAttachments',
    isPrivate: true,
    method: 'delete',
    path: '/courses/attachments/:id',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'projects',
    isPrivate: true,
    method: 'post',
    path: '/projects',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'projects',
    isPrivate: true,
    method: 'put',
    path: '/projects',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'projectImagesCarousel',
    isPrivate: true,
    method: 'post',
    path: '/projects/images',
    roles: allRolesPermission,
  },
  {
    action: 'setDefault',
    controller: 'projectImagesCarousel',
    isPrivate: true,
    method: 'post',
    path: '/projects/images/default',
    roles: allRolesPermission,
  },
  {
    action: 'deleteImage',
    controller: 'projectImagesCarousel',
    isPrivate: true,
    method: 'delete',
    path: '/projects/images/:id',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'actions',
    method: 'post',
    isPrivate: true,
    path: '/actions',
    roles: allRolesPermission,
  },
  {
    action: 'deleteAction',
    controller: 'actions',
    method: 'delete',
    isPrivate: true,
    path: '/actions/:id',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'actions',
    isPrivate: true,
    method: 'put',
    path: '/actions',
    roles: allRolesPermission,
  },
  {
    action: 'publish',
    controller: 'actions',
    isPrivate: true,
    method: 'post',
    path: '/actions/publish',
    roles: allRolesPermission,
  },
  {
    action: 'search',
    controller: 'actions',
    isPrivate: true,
    method: 'get',
    path: '/actions',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSV',
    controller: 'actions',
    isPrivate: true,
    method: 'get',
    path: '/actions/download',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'actions',
    isPrivate: true,
    method: 'post',
    path: '/actions',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'actionImagesCarousel',
    method: 'post',
    isPrivate: true,
    path: '/actions/images',
    roles: allRolesPermission,
  },
  {
    action: 'setDefault',
    controller: 'actionImagesCarousel',
    isPrivate: true,
    method: 'post',
    path: '/actions/images/default',
    roles: allRolesPermission,
  },
  {
    action: 'deleteImage',
    controller: 'actionImagesCarousel',
    method: 'delete',
    isPrivate: true,
    path: '/actions/images/:id',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'actionAttachments',
    isPrivate: true,
    method: 'post',
    path: '/actions/attachments',
    roles: allRolesPermission,
  },
  {
    action: 'deleteAttachment',
    controller: 'actionAttachments',
    isPrivate: true,
    method: 'delete',
    path: '/actions/:idAction/attachments/:id',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'actionAttachments',
    isPrivate: true,
    method: 'put',
    path: '/actions/attachments',
    roles: allRolesPermission,
  },
  {
    action: 'deleteUserRating',
    controller: 'actionUserRatings',
    method: 'delete',
    isPrivate: true,
    path: '/actions/:id/rating',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'users',
    isPrivate: true,
    method: 'post',
    path: '/users/create',
    roles: allRolesPermission,
  },
  {
    action: 'findAll',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'post',
    path: '/dnit/units',
    roles: allRolesPermission,
  },
  {
    action: 'findById',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'get',
    path: '/dnit/units/:id',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'post',
    path: '/dnit/unit',
    roles: allRolesPermission,
  },
  {
    action: 'search',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'get',
    path: '/dnit-units/search',
    roles: allRolesPermission,
  },
  {
    action: 'findAllCMS',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'get',
    path: '/dnit-units/findAll',
    roles: allRolesPermission,
  },
  {
    action: 'canRemove',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'get',
    path: '/dnit/units/:id/check',
    roles: allRolesPermission,
  },
  {
    action: 'findAllRegionalSuperintendence',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'get',
    path: '/dnit-units/superintendences/',
    roles: allRolesPermission,
  },
  {
    action: 'findAllLocalUnits',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'get',
    path: '/dnit-units/locals',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'put',
    path: '/dnit/unit',
    roles: allRolesPermission,
  },
  {
    action: 'createLocalunit',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'post',
    path: '/dnit/units/local',
    roles: allRolesPermission,
  },
  {
    action: 'searchLocalUnit',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'get',
    path: '/dnit/units/local/search',
    roles: allRolesPermission,
  },
  {
    action: 'updatelocalUnit',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'put',
    path: '/dnit/units/local',
    roles: allRolesPermission,
  },
  {
    action: 'getDnitUnitCities',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'get',
    path: '/dnit/units/:id/cities',
    roles: allRolesPermission,
  },
  {
    action: 'findAllDnitUnitByCities',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'get',
    path: '/dnit/units-by-cities/:id',
    roles: allRolesPermission,
  },
  {
    action: 'canRemove',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'get',
    path: '/dnit/units/:id/check',
    roles: allRolesPermission,
  },
  {
    action: 'remove',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'delete',
    path: '/dnit/units/:id',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSV',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'post',
    path: '/dnit/units/download',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'institutions',
    isPrivate: true,
    method: 'post',
    path: '/institutions',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'institutions',
    isPrivate: true,
    method: 'put',
    path: '/institutions',
    roles: allRolesPermission,
  },
  {
    action: 'deleteById',
    controller: 'institutions',
    isPrivate: true,
    method: 'delete',
    path: '/institutions/:id',
    roles: allRolesPermission,
  },
  {
    action: 'canRemove',
    controller: 'institutions',
    isPrivate: true,
    method: 'get',
    path: '/institutions/:id/check',
    roles: allRolesPermission,
  },
  {
    action: 'searchInstitution',
    controller: 'institutions',
    isPrivate: false,
    method: 'get',
    path: '/institutions',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSV',
    controller: 'institutions',
    isPrivate: true,
    method: 'get',
    path: '/institutions/download/',
    roles: allRolesPermission,
  },
  {
    action: 'getById',
    controller: 'institutions',
    isPrivate: true,
    method: 'get',
    path: '/institutions/:id',
    roles: allRolesPermission,
  },
  {
    action: 'findCodeInep',
    controller: 'institutions',
    isPrivate: true,
    method: 'post',
    path: '/institutions/codeinep',
    roles: allRolesPermission,
  },
  {
    action: 'setUserAvatar',
    controller: 'userAttachments',
    isPrivate: true,
    method: 'post',
    path: '/users/:idUser/avatar',
    roles: allRolesPermission,
  },
  {
    action: 'searchAndListUsersCMS',
    controller: 'users',
    isPrivate: true,
    method: 'get',
    path: '/users/search',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSV',
    controller: 'users',
    isPrivate: true,
    method: 'get',
    path: '/users/download',
    roles: allRolesPermission,
  },
  {
    action: 'findAllCMS',
    controller: 'userRoles',
    isPrivate: true,
    method: 'get',
    path: '/users/roles',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'users',
    isPrivate: true,
    method: 'put',
    path: '/users',
    roles: allRolesPermission,
  },
  {
    action: 'findByDnitUnit',
    controller: 'roads',
    isPrivate: true,
    method: 'get',
    path: '/dnit-units/roads',
    roles: allRolesPermission,
  },
  {
    action: 'findByUf',
    controller: 'roads',
    isPrivate: true,
    method: 'get',
    path: '/dnit-units/roads/uf',
    roles: allRolesPermission,
  },
  {
    action: 'findAllCMS',
    controller: 'themes',
    isPrivate: true,
    method: 'get',
    path: '/themes',
    roles: allRolesPermission,
  },
  {
    action: 'findAllCMS',
    controller: 'subThemes',
    isPrivate: true,
    method: 'get',
    path: '/subthemes',
    roles: allRolesPermission,
  },
  {
    action: 'findAllByTheme',
    controller: 'subThemes',
    isPrivate: true,
    method: 'get',
    path: '/themes/:idTheme/subthemes',
    roles: allRolesPermission,
  },
  {
    action: 'findAllCMS',
    controller: 'trafficConcept',
    isPrivate: true,
    method: 'get',
    path: '/trafficConcepts',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'trafficConcept',
    isPrivate: true,
    method: 'post',
    path: '/trafficConcepts',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'trafficConcept',
    isPrivate: true,
    method: 'put',
    path: '/trafficConcepts',
    roles: allRolesPermission,
  },
  {
    action: 'download',
    controller: 'trafficConcept',
    isPrivate: true,
    method: 'get',
    path: '/trafficConcepts/download',
    roles: allRolesPermission,
  },
  {
    action: 'remove',
    controller: 'trafficConcept',
    isPrivate: true,
    method: 'delete',
    path: '/trafficConcepts/:id',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'trafficContent',
    isPrivate: true,
    method: 'post',
    path: '/trafficContents',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'trafficContent',
    isPrivate: true,
    method: 'put',
    path: '/trafficContents',
    roles: allRolesPermission,
  },
  {
    action: 'findAllCMS',
    controller: 'trafficContent',
    isPrivate: true,
    method: 'get',
    path: '/trafficContents',
    roles: allRolesPermission,
  },
  {
    action: 'download',
    controller: 'trafficContent',
    isPrivate: true,
    method: 'get',
    path: '/trafficContents/download',
    roles: allRolesPermission,
  },
  {
    action: 'remove',
    controller: 'trafficContent',
    isPrivate: true,
    method: 'delete',
    path: '/trafficContents/:id',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'knowledgeObjects',
    method: 'post',
    path: '/knowledgeObjects',
    roles: allRolesPermission,
  },
  {
    action: 'search',
    controller: 'knowledgeObjects',
    method: 'get',
    path: '/knowledgeObjects',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSV',
    controller: 'knowledgeObjects',
    method: 'get',
    path: '/knowledgeObjects/download',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'knowledgeObjects',
    method: 'put',
    path: '/knowledgeObjects',
    roles: allRolesPermission,
  },
  {
    action: 'remove',
    controller: 'knowledgeObjects',
    method: 'delete',
    path: '/knowledgeObjects/:id',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'activities',
    isPrivate: true,
    method: 'post',
    path: '/activities',
    roles: allRolesPermission,
  },
  {
    action: 'cmsSearch',
    controller: 'activities',
    isPrivate: true,
    method: 'get',
    path: '/activities',
    roles: allRolesPermission,
  },
  {
    action: 'download',
    controller: 'activities',
    isPrivate: true,
    method: 'get',
    path: '/activities/download',
    roles: allRolesPermission,
  },
  {
    action: 'remove',
    controller: 'activities',
    isPrivate: true,
    method: 'delete',
    path: '/activities/:id',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'activities',
    isPrivate: true,
    method: 'put',
    path: '/activities',
    roles: allRolesPermission,
  },
  {
    action: 'publish',
    controller: 'activities',
    isPrivate: true,
    method: 'post',
    path: '/activities/publish',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'activityAttachments',
    isPrivate: true,
    method: 'post',
    path: '/activities/attachments',
    roles: allRolesPermission,
  },
  {
    action: 'remove',
    controller: 'activityAttachments',
    isPrivate: true,
    method: 'delete',
    path: '/activities/attachments/:id',
    roles: allRolesPermission,
  },
  {
    action: 'activate',
    controller: 'users',
    isPrivate: true,
    method: 'put',
    path: '/users/activate',
    roles: allRolesPermission,
  },
  {
    action: 'getById',
    controller: 'users',
    isPrivate: true,
    method: 'get',
    path: '/users/:id',
    roles: allRolesPermission,
  },
  {
    action: 'search',
    controller: 'trafficScope',
    isPrivate: true,
    method: 'get',
    path: '/trafficScopes',
    roles: allRolesPermission,
  },
  {
    action: 'search',
    controller: 'projects',
    isPrivate: true,
    method: 'get',
    path: '/projects',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSV',
    controller: 'projects',
    isPrivate: true,
    method: 'get',
    path: '/projects/download',
    roles: allRolesPermission,
  },
  {
    action: 'deleteProject',
    controller: 'projects',
    isPrivate: true,
    method: 'delete',
    path: '/projects/:idProject',
    roles: allRolesPermission,
  },
  {
    action: 'publish',
    controller: 'projects',
    isPrivate: true,
    method: 'post',
    path: '/projects/publish',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'projectAttachments',
    isPrivate: true,
    method: 'post',
    path: '/projects/attachments',
    roles: allRolesPermission,
  },
  {
    action: 'deleteAttachment',
    controller: 'projectAttachments',
    isPrivate: true,
    method: 'delete',
    path: '/projects/:idProject/attachments/:id',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'externalLinks',
    isPrivate: true,
    method: 'post',
    path: '/externalLinks',
    roles: allRolesPermission,
  },
  {
    action: 'deleteExternalLink',
    controller: 'externalLinks',
    isPrivate: true,
    method: 'delete',
    path: '/externalLink/:id',
    roles: allRolesPermission,
  },
  {
    action: 'search',
    controller: 'externalLinks',
    isPrivate: true,
    method: 'get',
    path: '/externalLinks',
    roles: allRolesPermission,
  },
  {
    action: 'findById',
    controller: 'externalLinks',
    method: 'get',
    path: '/externalLink/:id',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSV',
    controller: 'externalLinks',
    isPrivate: true,
    method: 'get',
    path: '/externalLinks/download',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'externalLinks',
    isPrivate: true,
    method: 'put',
    path: '/externalLinks',
    roles: allRolesPermission,
  },
  {
    action: 'publish',
    controller: 'externalLinks',
    isPrivate: true,
    method: 'post',
    path: '/externalLinks/publish',
    roles: allRolesPermission,
  },
  {
    action: 'listHighlightItems',
    controller: 'highlights',
    isPrivate: true,
    method: 'get',
    path: '/highlights',
    roles: allRolesPermission,
  },
  {
    action: 'listHighlightTypes',
    controller: 'highlights',
    isPrivate: true,
    method: 'get',
    path: '/highlights/types',
    roles: allRolesPermission,
  },
  {
    action: 'updateHighlightItems',
    controller: 'highlights',
    isPrivate: true,
    method: 'post',
    path: '/highlights',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSV',
    controller: 'highlights',
    isPrivate: true,
    method: 'get',
    path: '/highlights/download',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'projectActions',
    method: 'post',
    isPrivate: true,
    path: '/projectActions',
    roles: allRolesPermission,
  },
  {
    action: 'deleteAction',
    controller: 'projectActions',
    method: 'delete',
    isPrivate: true,
    path: '/projectActions/:id',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'projectActions',
    isPrivate: true,
    method: 'put',
    path: '/projectActions',
    roles: allRolesPermission,
  },
  {
    action: 'publish',
    controller: 'projectActions',
    isPrivate: true,
    method: 'post',
    path: '/projectActions/publish',
    roles: allRolesPermission,
  },
  {
    action: 'search',
    controller: 'projectActions',
    isPrivate: true,
    method: 'get',
    path: '/projectActions',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSV',
    controller: 'projectActions',
    isPrivate: true,
    method: 'get',
    path: '/projectActions/download',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'projectActions',
    isPrivate: true,
    method: 'post',
    path: '/projectActions',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'projectActionsImagesCarousel',
    method: 'post',
    isPrivate: true,
    path: '/projectActions/images',
    roles: allRolesPermission,
  },
  {
    action: 'setDefault',
    controller: 'projectActionsImagesCarousel',
    isPrivate: true,
    method: 'post',
    path: '/projectActions/images/default',
    roles: allRolesPermission,
  },
  {
    action: 'deleteImage',
    controller: 'projectActionsImagesCarousel',
    method: 'delete',
    isPrivate: true,
    path: '/projectActions/images/:id',
    roles: allRolesPermission,
  },
  {
    action: 'create',
    controller: 'projectActionsAttachments',
    isPrivate: true,
    method: 'post',
    path: '/projectActions/attachments',
    roles: allRolesPermission,
  },
  {
    action: 'deleteAttachment',
    controller: 'projectActionsAttachments',
    isPrivate: true,
    method: 'delete',
    path: '/projectActions/:idAction/attachments/:id',
    roles: allRolesPermission,
  },
  {
    action: 'update',
    controller: 'projectActionsAttachments',
    isPrivate: true,
    method: 'put',
    path: '/projectActions/attachments',
    roles: allRolesPermission,
  },
  {
    action: 'deleteUserRating',
    controller: 'projectActionUserRatings',
    method: 'delete',
    isPrivate: true,
    path: '/projectActions/:id/rating',
    roles: allRolesPermission,
  },
  {
    action: 'findAllToEvaluate',
    controller: 'initiative',
    isPrivate: true,
    method: 'get',
    path: '/initiatives/evaluate',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSVToEvaluate',
    controller: 'initiative',
    isPrivate: true,
    method: 'get',
    path: '/initiatives/evaluate/download',
    roles: allRolesPermission,
  },
  {
    action: 'findAllToPublish',
    controller: 'initiative',
    isPrivate: true,
    method: 'get',
    path: '/initiatives/publish',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSVToPublish',
    controller: 'initiative',
    isPrivate: true,
    method: 'get',
    path: '/initiatives/publish/download',
    roles: allRolesPermission,
  },
  {
    action: 'findAllToVisualization',
    controller: 'initiative',
    isPrivate: true,
    method: 'get',
    path: '/initiatives/visualization',
    roles: allRolesPermission,
  },
  {
    action: 'downloadCSVToVisualization',
    controller: 'initiative',
    isPrivate: true,
    method: 'get',
    path: '/initiatives/visualization/download',
    roles: allRolesPermission,
  },
  {
    action: 'saveEvaluation',
    controller: 'initiativeEvaluation',
    method: 'post',
    path: '/initiative/evaluate',
    roles: allRolesPermission,
  },
  {
    action: 'save',
    controller: 'initiativePublish',
    method: 'post',
    path: '/initiative/publish',
    roles: allRolesPermission,
  },
  {
    action: 'download',
    controller: 'survey',
    exact: true,
    isPrivate: true,
    method: 'get',
    path: '/survey/download',
    roles: allRolesPermission,
  },
  {
    action: 'findAll',
    controller: 'survey',
    isPrivate: true,
    method: 'get',
    path: '/survey',
    roles: allRolesPermission,
  },
  {
    action: 'countAll',
    controller: 'survey',
    isPrivate: true,
    method: 'get',
    path: '/survey/countAll',
    roles: allRolesPermission,
  },
  {
    action: 'getSurveyById',
    controller: 'survey',
    exact: true,
    isPrivate: true,
    method: 'get',
    path: '/survey/:id',
    roles: allRolesPermission,
  },
  {
    action: 'createSurvey',
    controller: 'survey',
    isPrivate: true,
    method: 'post',
    path: '/survey',
    roles: allRolesPermission,
  },
  {
    action: 'getAllUsers',
    controller: 'dnitUnit',
    isPrivate: true,
    method: 'get',
    path: '/dnit/users',
    roles: allRolesPermission,
  },
  {
    action: 'startCron',
    controller: 'messages',
    exact: true,
    isPrivate: true,
    method: 'get',
    path: '/messages/startCron',
    roles: [admin],
  },
  {
    action: 'releaseAccess',
    controller: 'users',
    isPrivate: true,
    method: 'post',
    path: '/users/releaseAccess',
    roles: allRolesPermission,
  }
];
